name: tcc-api
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.*
  - uvicorn
  - fastapi
  - pydantic
  - httpx
  - pytest
  - pytest-asyncio
  - libstdcxx-ng>=13
  - libgcc-ng>=13
  - icu
  - sqlite
